first_project/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('', views.index,name='index'),
    path('form/', views.profile_form_view,name='profile_form'),
    path('contact/', views.contact,name='contact'),
    path('relative/', views.relative,name='relative'),
    path('register/', views.register,name='register'),
    path('user_login/', views.user_login,name='user_login'),
    path('user_logout/', views.user_logout,name='user_logout'),
    path('special/', views.special,name='special'),
]

first_project/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index,name='index'),
    path('signup/', views.signup,name='signup'),

]

first_project/first_app/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'

urlpatterns = [
    path('', views.index,name='index'),

]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from basicapp import views


urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('basicapp/', include('basicapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

first_project/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/community/models.py
from django.db import models

# Create your models here.

class Human(models.Model):
    last_name = models.CharField(max_length=264,unique=True)
    first_name = models.CharField(max_length=264)
    email = models.EmailField()

    def __str__(self):
        return self.last_name + ", " + self.first_name

    class Meta:
        app_label = "community"

first_project/first_app/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    topic_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.topic_name

    class Meta:
        app_label = "first_app"

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        app_label = "first_app"

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

    class Meta:
        app_label = "first_app"

first_project/basicapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class ProfileForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['verify_email']
        if email != vemail:
            raise forms.ValidationError("Make sure your emails match.")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/community/forms.py
from django import forms
from .models import Human

class NewHumanForm(forms.ModelForm):
    class Meta:
        model = Human
        fields = '__all__'

first_project/basicapp/views.py
from django.shortcuts import render
from basicapp import forms
from basicapp.forms import UserForm,UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basicapp/index.html', context_dict)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in.")

def profile_form_view(request):
    form = forms.ProfileForm()

    if request.method == 'POST':

        form = forms.ProfileForm(request.POST)

        if form.is_valid():
            print("Validation success!")
            print("Name: " + form.cleaned_data['name'])
            print("Email: " + form.cleaned_data['email'])
            print("Text: " + form.cleaned_data['text'])

    return render(request, 'basicapp/form_page.html', {'form':form})

def contact(request):
    return render(request, 'basicapp/contact.html')

def relative(request):
    return render(request, 'basicapp/relative_url_templates.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'basicapp/registration.html', {'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:

            if user.is_active:

                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:

        return render(request,'basicapp/login.html',{})

first_project/community/views.py
from django.shortcuts import render
# from django.http import HttpResponse
# from .models import Human
from .forms import NewHumanForm

# Create your views here.
def index(request):
    return render(request,'community/index.html')

def signup(request):

    form = NewHumanForm()

    if request.method == 'POST':
        form = NewHumanForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("Form invalid")

    return render(request,'community/signup.html',{'form':form})

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord
# Create your views here.










def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    return render(request,'first_app/index.html',context=date_dict)

first_project/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'basicapp:index' %}">MADISON PACIFIC</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basicapp:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basicapp:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                      {% if user.is_authenticated %}
                      <a class="nav-link" href="{% url 'basicapp:user_logout' %}">Logout</a>
                      {% else %}
                      <a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
                      {% endif %}
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'basicapp:contact' %}">Contact</a>
                    </li>
                  </ul>
            </div>
        </nav>

      </div>
    </nav>
    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

first_project/templates/basicapp/contact.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}

  {% block body_block %}
    <h1>Contact us!</h1>
    <p>This is an example of template inheritance.</p>
  {% endblock %}

first_project/templates/basicapp/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title></title>
  </head>
  <body>

    <div class="m-2 p-3 bg-light rounded-3">
      <h1 class="display-4">Fill up the form!</h1>
      <hr class="my-4">
      <form class="" method="post">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" name="Submit" value="Submit">
      </form>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

first_project/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>Index</h1>
    <p>The first variable is: {{ text|exclaim:"l"|upper }}</p>
    <p>The second number is: {{ number|add:"99" }}</p>
  {% endblock %}

first_project/templates/basicapp/login.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load my_extras %}
{% load static %}

  {% block body_block %}
    <h1>Log In</h1>

    <p>Enter your login details:</p>

    <form class="" action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input type="password" name="password">
        <input type="Submit" name="" value="Login">
    </form>


  {% endblock %}

first_project/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load my_extras %}
{% load static %}

  {% block body_block %}
    <h1>Registration</h1>
    {% if registered %}
    <p>Thank you for registering!</p>
    {% else %}
    <p>Fill up the form:</p>
    <form class="" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}

  {% endblock %}

first_project/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Welcome to Basic app</title>
  </head>
  <body>
    <div class="m-2 p-3 bg-light rounded-3">
      <h1 class="display-4">Welcome to Relative URL Templates!</h1>
      <hr class="my-4">
      <a href="{% url 'index' %}">Index</a>
      <a href="{% url 'basicapp:contact' %}">Contact</a>
      <a href="{% url 'basicapp:index' %}">Index</a>
      <a href="{% url 'basicapp:profile_form' %}">Form</a>
      <a href="{% url 'admin:index' %}">Admin</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

first_project/templates/community/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Welcome to Basic app</title>
  </head>
  <body>
    <div class="m-2 p-3 bg-light rounded-3">
      <h1 class="display-4">Welcome to our community!</h1>
      <hr class="my-4"
      <p>Go to /signup to fill in the form</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

first_project/templates/community/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Sign up!</title>
  </head>
  <body>
s
    <div class="m-2 p-3 bg-light rounded-3">
      <h1 class="display-4">Sign up to join our community!</h1>
      <hr class="my-4">
      <form class="" method="post">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" name="" value="Submit">
      </form>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  </head>
  <body>
    <h1>Welcome to Django Level 2.</h1>
    <h2>Here are your access records:</h2>

    <div class="djangtwo">
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        {% for record in access_records %}
        <tr>
          <td>{{ record.name }}</td>
          <td>{{ record.date }}</td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <p>No access records found.</p>
      {% endif %}
    </div>
  </body>
</html>